(function(){
'use strict';
var views=[].slice.call(document.querySelectorAll('.view'));
var toast=document.getElementById('toast');
var state={theme:'dark',font:16,lastView:'home'};
function $(id){return document.getElementById(id)}
function clean(v,f){v=String(v||'').trim();return v||f||''}
function notify(m){toast.textContent=m;toast.classList.add('show');window.clearTimeout(notify.t);notify.t=window.setTimeout(function(){toast.classList.remove('show')},1600)}
function show(name){views.forEach(function(v){v.classList.toggle('active',v.dataset.view===name)});state.lastView=name;try{window.scrollTo(0,0)}catch(e){}savePrefs()}
function savePrefs(){try{localStorage.setItem('aacs-v22-prefs',JSON.stringify(state))}catch(e){}}
function restorePrefs(){try{var x=JSON.parse(localStorage.getItem('aacs-v22-prefs')||'null');if(x){state.theme=x.theme||'dark';state.font=x.font||16}}catch(e){}applyTheme();applyFont()}
function applyTheme(){document.body.classList.toggle('light',state.theme==='light');$('themeBtn').textContent=state.theme==='light'?'☾':'☀︎'}
function applyFont(){document.documentElement.style.setProperty('--fs',state.font+'px')}
function copyText(text){if(!text){notify('目前沒有可複製內容');return}if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(text).then(function(){notify('已複製')}).catch(function(){fallbackCopy(text)})}else{fallbackCopy(text)}}
function fallbackCopy(text){var ta=document.createElement('textarea');ta.value=text;ta.setAttribute('readonly','');ta.style.position='fixed';ta.style.opacity='0';ta.style.left='-9999px';document.body.appendChild(ta);ta.select();ta.setSelectionRange(0,ta.value.length);try{document.execCommand('copy');notify('已複製')}catch(e){notify('請長按文字手動複製')}document.body.removeChild(ta)}
var adapterNames={universal:'通用圖生圖',chatgpt:'ChatGPT Images',gemini:'Gemini Images',midjourney:'Midjourney',ideogram:'Ideogram',flux:'FLUX / ComfyUI',custom:'自訂／其他'};
function textInstruction(mode,title){if(mode==='none')return 'Do not add any text, letters, logos or typographic elements.';if(mode==='space')return 'Do not render the final wording. Reserve a clean, elegant physical plaque or sign area for later typography post-production.';return 'Integrate the exact Traditional Chinese title “'+title+'” as clean, legible physical lettering; prioritize character accuracy and do not invent extra text.'}
function fidelityInstruction(v){if(v==='faithful')return 'Preserve the hero subject, pose, expression, identity cues and overall visual hierarchy very closely.';if(v==='creative')return 'Keep the unmistakable hero identity but allow a more imaginative spatial reconstruction into a miniature collectible world.';return 'Preserve the unmistakable hero identity and emotional tone while moderately rebuilding the surroundings into a coherent miniature world.'}
function adapterIntro(target){if(target==='chatgpt')return 'Use the image already attached in this conversation as the visual reference. Follow the transformation instructions below directly.';if(target==='gemini')return 'Use the image currently provided to the image generator as the primary reference and transform it according to the following art direction.';if(target==='midjourney')return 'Use the reference image already supplied in your Midjourney workflow as the dominant subject/composition reference; treat the text below as art direction, not as a request to invent a new unrelated subject.';if(target==='ideogram')return 'Use the uploaded reference image as the primary visual reference, with special care for clean layout and any requested typography.';if(target==='flux')return 'Image-to-image direction: use the loaded reference image as the source identity/composition anchor; preserve the hero while rebuilding the environment according to this prompt.';if(target==='custom')return 'Use the reference image you have already loaded in this image-generation app as the primary visual source.';return 'Use the uploaded reference image as the primary visual reference.'}
function adapterTail(target){if(target==='midjourney')return ' Keep one clear hero subject and strong silhouette. Apply your preferred image-reference strength inside Midjourney rather than inventing extra subjects.';if(target==='ideogram')return ' Keep typography isolated on a simple physical sign surface if text rendering is enabled.';if(target==='flux')return ' Keep denoise/image-to-image strength moderate enough to retain the hero identity; tune this in your own FLUX/ComfyUI workflow.';return ''}
function quickPrompt(){var target=$('qTarget').value,template=$('qTemplate').value,world=$('qWorld').value,material=$('qMaterial').value,core=clean($('qCore').value,'the unmistakable hero subject and signature motifs from the reference image'),title=clean($('qTitle').value,'開運招福'),ratio=$('qRatio').value,textMode=$('qTextMode').value,strength=$('qStrength').value;return adapterIntro(target)+'\n\nTransform the reference into a premium museum-grade miniature '+template+'. '+fidelityInstruction(strength)+' Preserve these confirmed core elements: '+core+'. Do not replace the hero with unrelated objects.\n\nRebuild the scene as a true three-dimensional MiniWorld rather than simply placing the flat reference image inside a container. Core world: '+world+'. Primary materials: '+material+'. Create layered foreground, midground and background, handcrafted miniature architecture/props appropriate to the reference, believable scale cues, and a polished collectible-object presentation.\n\n'+textInstruction(textMode,title)+'\n\nVisual quality: cinematic macro photography, tilt-shift miniature scale, convincing handcrafted detail, realistic material response, glass reflections and refraction where applicable, volumetric light, shallow depth of field, elegant negative space, premium 2026 collectible presentation, strong subject separation. Composition '+ratio+'. No duplicated hero, no duplicated landmarks, no distorted face, no extra limbs or paws, no garbled text, no watermark, no logo, no competing focal point.'+adapterTail(target)}
function plaqueText(){var n=clean($('recipient').value,'收藏者'),p=$('plaquePattern').value;if(p==='collection')return n+' · 雅藏';if(p==='gift')return '敬贈　'+n;if(p==='treasure')return '贈予'+n+' · 珍藏';if(p==='madefor')return '為'+n+'珍藏而作';return clean($('plaqueCustom').value,n+' · 雅藏')}
function syncPlaque(){if($('plaquePattern').value!=='custom')$('plaqueCustom').value=plaqueText()}
function fullPrompt(){var title=clean($('title').value,'未命名作品'),recipient=clean($('recipient').value,'收藏者'),blessing=clean($('blessing').value,'願日日安好'),brief=clean($('referenceBrief').value,'the unmistakable hero subject from the reference image'),plaque=clean($('plaqueCustom').value,plaqueText());return 'Create a premium personalized AI art collectible, presented as a museum-grade '+$('template').value+'. Use the reference image already provided to the chosen image generator and preserve its emotional identity. Retain these confirmed core elements: '+brief+'. Rebuild them as a coherent miniature collectible world rather than a flat image-in-container effect. Core world: '+$('world').value+'. Primary materials: '+$('material').value+'. Main artwork title in accurate Traditional Chinese: “'+title+'”. Integrate the dedication as a refined '+($('scrollMode').value==='scroll'?'classical Chinese hanging scroll with calligraphy, restrained seals and aged silk-paper texture':'formal collector inscription')+': “'+blessing+'”. The base must carry a sophisticated gold recessed / relief seal-script-and-clerical-script inspired inscription: “'+plaque+'”. Collector / recipient: “'+recipient+'”. Include Edition '+clean($('edition').value,'No. 001 / 001')+' and artist signature / provenance “'+clean($('signature').value,'')+'” discreetly on a rear or secondary plaque, not competing with the hero artwork. Use cinematic macro photography, convincing miniature scale, handcrafted detail, realistic reflections/refraction where applicable, volumetric light, shallow depth of field, elegant negative space, premium 2026 collectible presentation, strong subject separation, no duplicated hero or landmarks, no garbled text, no watermark, no extra limbs, no competing focal point.'}
function resetQuick(){$('qTarget').value='universal';$('qTemplate').value='琉璃宮燈世界';$('qWorld').value='未來光境 × 日式開運庭園';$('qMaterial').value='琉璃 × 黃銅 × 金箔';$('qCore').value='抬起右前掌的橘白招福貓、溫柔表情、金色鈴鐺與開運吊牌、粉色櫻花、富士山、紅色鳥居、金元寶、福袋、金幣與開運招福氛圍';$('qTitle').value='開運招福';$('qRatio').value='9:16';$('qTextMode').value='strict';$('qStrength').value='balanced';$('quickOutputPanel').hidden=true;notify('已恢復招福貓範例')}
document.querySelectorAll('[data-mode]').forEach(function(b){b.addEventListener('click',function(){show(b.dataset.mode)})});document.querySelectorAll('[data-go]').forEach(function(b){b.addEventListener('click',function(){show(b.dataset.go)})});
$('helpBtn').addEventListener('click',function(){show('help')});$('themeBtn').addEventListener('click',function(){state.theme=state.theme==='dark'?'light':'dark';applyTheme();savePrefs()});$('fontBtn').addEventListener('click',function(){state.font=state.font>=20?16:state.font+2;applyFont();savePrefs();notify('字體 '+state.font+'px')});
$('quickGenerate').addEventListener('click',function(){var out=quickPrompt();$('quickOutput').textContent=out;$('adapterName').textContent=adapterNames[$('qTarget').value];$('quickHint').textContent='下一步：回到 '+adapterNames[$('qTarget').value]+'，確認參考圖仍已載入，再貼上這段指令生成。';$('quickOutputPanel').hidden=false;notify('快速指令已生成')});$('copyQuick').addEventListener('click',function(){copyText($('quickOutput').textContent)});$('quickReset').addEventListener('click',resetQuick);
$('recipient').addEventListener('input',function(){syncPlaque()});$('plaquePattern').addEventListener('change',function(){syncPlaque()});$('plaqueCustom').addEventListener('input',function(){$('plaquePattern').value='custom'});$('fullGenerate').addEventListener('click',function(){syncPlaque();var p=fullPrompt();$('fullOutput').textContent=p;$('collectorCard').textContent='《'+clean($('title').value,'未命名作品')+'》｜'+$('template').value+'｜收藏者：'+clean($('recipient').value,'—')+'｜銘牌：'+plaqueText()+'｜Edition：'+clean($('edition').value,'—');$('fullOutputPanel').hidden=false;notify('收藏級 Prompt 已生成')});$('copyFull').addEventListener('click',function(){copyText($('fullOutput').textContent)});
document.querySelectorAll('[data-guide]').forEach(function(b){b.addEventListener('click',function(){document.querySelectorAll('[data-guide]').forEach(function(x){x.classList.toggle('active',x===b)});document.querySelectorAll('.guide-page').forEach(function(p){p.classList.toggle('active',p.id===b.dataset.guide)})})});
restorePrefs();syncPlaque();
})();